name: Test and deploy

on:
  push:
    branches: [main]


jobs:

  test:
    name: Test
    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v3


      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'


      - name: Pip install
        uses: py-actions/py-dependency-install@v4
        with:
              path: "requirements.txt"


      - name: Flake
        run: flake8 --exclude venv,sanitycheck.py


      - name: Create model dir
        run: mkdir model


      - name: Train Model
        run: python train_model.py


      - name: Run Tests
        run: pytest tests

